# -*- coding: utf-8 -*-
"""ExerciciosPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ndWNQAKigiC1qFQMldqgUDE6VVk9_hrq
"""

primeiro_valor = float(input("Digite o primeiro valor: "))

segundo_valor = float(input("Digite o segundo valor: "))



soma = primeiro_valor + segundo_valor

subtracao = primeiro_valor - segundo_valor

multiplicacao = primeiro_valor * segundo_valor

divisao = primeiro_valor / segundo_valor

resto = primeiro_valor % segundo_valor

print(soma)

print("soma")

print(subtracao)

print(multiplicacao)

print(divisao)

print(resto)

#exemplo de calculo de media, onde o aluno vai inserir a nota das provas e o algoritimo ira calcular se esta aprovado ou nao

primeira_nota = float(input("digite a nota da primeira prova"))
segunda_nota = float(input("digite a nota da segunda prova"))
terceira_nota = float(input("digite a nota da terceira prova"))

soma = (primeira_nota + segunda_nota + terceira_nota)

media = (soma / 3)

if media >= 7 : print(f"voce foi aprovado com nota {media}")

#calcular a idade do usuario apenas perguntando a data de nascimento e verificando se ja fez aniversario esse ano


ano_nascimento = int(input("digite o ano do seu nascimento"))
ano_atual = 2023

idade = (ano_atual - ano_nascimento)

pergunta = input("Voce ja fez aniversario esse ano ?")

if pergunta == "nao": idade -= 1

print(f"sua idade é {idade}")

#exercicio de fixacao1
#Perguntar a idade do usuario e verificar se pode tirar a carteira ou nao

idade = int(input("Qual sua idade ?"))

if idade >= 18: print("boa, voce ja pode tirar a carteira de motorista")
else :
  print("infelizmente voce precisa esperar ter 18 para tirar a carteira de motorista")

#exercicio de fixacao2
#pedir o nome do usuario, se for maior que 20 char, falar para diminuir

nome = input("Informe seu nome completo para adicionar ao cartao")

if len(nome) > 20 : print("tente diminuir o nome, aceitamos no maximo 20 caracteres")
else :
  print("boa, nome inserido, seu cartao chegara em breve")

#exercicio de fixacao3
#verficar se o numero inserido e impar ou par

numero = int(input("Digite um numero para saber se e impar ou par"))

if (numero % 2) == 0 : print("esse numero e par")
else :
  print("esse numero e impar")

#exercicio de fixacao4
#perguntar o salario, se for acima de 5k, fazer um abono de 15%, se nao, fazer um abono de 10%

salario = float(input("digite seu salario"))

if salario > 5000 :
  abono = salario * 0.1
if salario < 5000 :
  abono = salario * 0.15

  print(f"seu salario no final do ano tera um abono de {abono:.2f}")

#exercicio de fixacao5
#perguntar em qual turno o usuario trabalha, verificar e cumprimentar corretamente

turno = input("Em qual turno voce trabalha ? (M-Manha T-Tarde N-Noite)")

if turno == "M" : print("Bom Dia!")
elif turno == "T": print("Boa Tarde!")
elif turno == "N": print("Boa Noite!")
else:
  print("valor invalido")

